name: Release Pipeline

on:
  push:
    tags:
      - '*'

jobs:
  linux_aarch64:
    name: Build LT for Linux (aarch64)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -P 'linux-aarch64, !win, !win-x86, !linux, !mac, !mac-aarch64'
    - run: mkdir staging && cd target && zip -r "../staging/Lilith's Throne (linux-aarch64).zip" "Lilith's Throne (linux-aarch64)/" && cd ..
    - uses: actions/upload-artifact@v4
      with:
        name: Lilith's Throne (linux-aarch64)
        path: 'staging'
  
  linux:
    name: Build LT for Linux (amd64)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -P 'linux, !win, !win-x86, !linux-aarch64, !mac, !mac-aarch64'
    - run: mkdir staging && cd target && zip -r "../staging/Lilith's Throne (linux).zip" "Lilith's Throne (linux)/" && cd ..
    - uses: actions/upload-artifact@v4
      with:
        name: Lilith's Throne (linux)
        path: 'staging'

  mac_aarch64:
    name: Build LT for Mac (aarch64)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -P 'mac-aarch64, !win, !win-x86, !linux, !linux-aarch64, !mac'
    - run: mkdir staging && cd target && zip -r "../staging/Lilith's Throne (mac-aarch64).zip" "Lilith's Throne (mac-aarch64)/" && cd ..
    - uses: actions/upload-artifact@v4
      with:
        name: Lilith's Throne (mac-aarch64)
        path: 'staging'

  mac:
    name: Build LT for Mac (amd64)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -P 'mac, !win, !win-x86, !linux, !linux-aarch64, !mac-aarch64'
    - run: mkdir staging && cd target && zip -r "../staging/Lilith's Throne (mac).zip" "Lilith's Throne (mac)/" && cd ..
    - uses: actions/upload-artifact@v4
      with:
        name: Lilith's Throne (mac)
        path: 'staging'

  win_x86:
    name: Build LT for Windows (x86)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean -B package --file pom.xml -P 'win-x86, !win, !linux, !linux-aarch64, !mac, !mac-aarch64'
    - run: mkdir staging && cd target && zip -r "../staging/Lilith's Throne (win-x86).zip" "Lilith's Throne (win-x86)/" && cd ..
    - uses: actions/upload-artifact@v4
      with:
        name: Lilith's Throne (win-x86)
        path: 'staging'
  
  win:
    name: Build LT for Windows (amd64)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -P 'win, !win-x86, !linux, !linux-aarch64, !mac, !mac-aarch64'
    - run: mkdir staging && cd target && zip -r "../staging/Lilith's Throne (win).zip" "Lilith's Throne (win)/" && cd ..
    - uses: actions/upload-artifact@v4
      with:
        name: Lilith's Throne (win)
        path: 'staging'
  
  build_release:
    needs: [linux_aarch64, linux, mac_aarch64, mac, win_x86, win]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Get Changelog File
        run: echo "CHANGELOG=$(ls -a ./res/patchNotes/ | grep -i .*-patchnotes-${GITHUB_REF#*/v}\.html)" >> $GITHUB_OUTPUT
        id: get_changelog

      - run: mkdir staging

      - name: donwload generated artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./staging
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ./res/patchNotes/${{ steps.get_changelog.outputs.CHANGELOG }}
          token: ${{ github.token }}
          files: |
            ./staging/Lilith's Throne (linux)/Lilith's Throne (linux).zip
            ./staging/Lilith's Throne (linux-aarch64)/Lilith's Throne (linux-aarch64).zip
            ./staging/Lilith's Throne (win)/Lilith's Throne (win).zip
            ./staging/Lilith's Throne (win-x86)/Lilith's Throne (win-x86).zip
            ./staging/Lilith's Throne (mac)/Lilith's Throne (mac).zip
            ./staging/Lilith's Throne (mac-aarch64)/Lilith's Throne (mac-aarch64).zip
